### ISSUE TITLE
Add, modify or remove entries.

### ISSUE THREAD

**Issue by cdamken** [alfredbuehler/bplog#1] opened 2019-03-08 16:11 UTC
It's not possible to edit any wrong entry or removes or add some entries that you have while you are not in front of the computer.

workaround modify in the database but you have to know the Unix timestamp to add it, but its dangerous to write in the db

**Comment by alfredbuehler** [comment] 2019-03-08 16:54
Well, no modification option is by design. You should not tweak the already existing records. 
And deleting of wrong or unwanted records is possible by the UI.

**Comment by cdamken** [comment] 2019-03-08 18:58
What is, if you typed something wrong and you have to correct the values? Then you have a different time when you try to enter again.

> And deleting of wrong or unwanted records is possible by the UI.

Now that you mentioned, well, just in a place, I didn't see at the beginning, only if you navigate over it.

<img width="1055" alt="screenshot 2019-03-08 at 11 53 59" src="https://user-images.githubusercontent.com/7264495/54048987-e1c70480-41a0-11e9-83a8-5c4becda278f.png">

> Well, no modification option is by design.

Modification is important for me to adjust it.

BTW , The program looks good and hopefully it would be great to have that modification option

**Comment by alfredbuehler** [comment] 2019-03-08 19:15
Thanks for your feedback! I'll think about your suggestions.

**Comment by alfredbuehler** [comment] 2019-04-27 10:26
Fixed by Release [v0.2.0](https://github.com/alfredbuehler/bplog/releases/tag/v0.2.0).

**Closed as completed by alfredbuehler** 2019-04-27 10:26 UTC

**Comment by cdamken** [comment] 2019-04-28 20:59
Thank you!, Now I can use it better, thank you very much
